version: "3"

networks:
  ttn:

services:
  grafana:
    image: fg2it/grafana-armhf:v4.6.3
    volumes:
    - /var/lib/grafana:/var/lib/grafana
    networks:
      ttn:
        aliases:
        - grafana
    ports:
    - "3000:3000"

  broker:
    image: emqttd-docker-v2.3.3
    environment:
      - EMQ_WAIT_TIME=60
      - EMQ_LOG__CONSOLE__LEVEL=error
      - EMQ_ADMIN_PASSWORD=not_the_default_one
      - EMQ_LOADED_PLUGINS=emq_recon,emq_modules,emq_retainer,emq_dashboard,emq_sn
      - EMQ_MQTT__SN__PORT=2883
      - EMQ_MQTT__SN__ENABLE_STATS=on
    networks:
      ttn:
        aliases:
          - broker
    ports:
      - "1883:1883"
      - "2883:2883/udp"
      # - "8083:8083"
      # - "8883:8883"
      # - "8084:8084"
      - "18083:18083"

  mqtt-bridge:
    image: eclipse-mosquitto
    depends_on:
      - broker
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      ttn:
        aliases:
          - mqtt-bridge

  postgres:
    build: ./postgres
    image: kiotlog/postgres
    networks:
      ttn:
        aliases:
          - catalog
          - postgres
    ports:
      - 127.0.0.1:7432:5432
    volumes:
      - /var/lib/postgres/10:/var/lib/postgresql/data

  api:
    image: kiotlog/klapi
    networks:
      ttn:
        aliases:
          - api
    ports:
      - 80:8888
    environment:
      - host=0.0.0.0
      - port=8888
      - pguser=kl_webapi
      - pgpass=KlW3b4p1
      - pghost=catalog
      - pgport=5432
      - pgdb=trmpln

  klhr:
    image: kiotlog/httpreceiver
    depends_on:
      - postgres
      - broker
    networks:
      ttn:
        aliases:
          - klhr
          - httpreceiver
    ports:
      - 8080:8080
    command: --host 0.0.0.0 --mqttbroker broker 1883 --postgres kl_httpreceiver KlR3c3iv3r postgres 5432 trmpln

  decoder:
    image: kiotlog/decoder
    depends_on:
      - postgres
      - broker
    networks:
      ttn:
        aliases:
          - decoder
    command: --mqttbroker broker 1883 --postgres kl_decoder KlD3c0d3r postgres 5432 trmpln --topics /+/+/devices/+/up

  klsn:
    image: kiotlog/klsnreceiver
    depends_on:
      - postgres
      - broker
    networks:
      ttn:
        aliases:
          - klsn
    command: --mqttbroker broker 1883 --postgres kl_snreceiver KLSnR3c3iv3r postgres 5432 trmpln

  # pyhttprecv:
  #   image: kiotlog/pyhttprecv
  #   networks:
  #     ttn:
  #       aliases:
  #         - pyhttprecv
  #   ports:
  #     - 5000:5000
  #   command: --pg-host postgres --pg-port 5432
