
version: "3"

networks:
  ttn:

services:
  nodered:
    image: nodered/node-red-docker
    volumes: 
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/nodered/data:/data
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/nodered/nodered_flows.json:/data/flows.json
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/nodered/nodered_settings.js:/data/settings.js
    networks:
      ttn:
        aliases:
        - mynodered
    ports:
      - "1880:1880"
  
  influxdb:
    image: influxdb:alpine
    volumes:
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=false
    networks:
      ttn:
        aliases:
        - influxdb
    ports:
    # - "8083:8083"
      - "127.0.0.1:8086:8086"

  grafana:
    image: grafana/grafana
    volumes:
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/grafana:/var/lib/grafana
    networks:
      ttn:
        aliases:
        - grafana
    ports:
    - "3000:3000"

  emqtt:
    image: emqttd-docker-v2.3.0
    volumes:
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/emqttd/etc:/opt/emqttd/etc
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/emqttd/data:/opt/emqttd/data
    networks:
      ttn:
        aliases:
          - emqtt
    ports:
      - "1883:1883"
      - "2883:2883/udp"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
  
  mqtt-bridge:
    image: eclipse-mosquitto
    depends_on:
      - emqtt
    volumes:
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks: 
      ttn:
        aliases:
          - mqtt-bridge

  postgres:
    build: ./postgres
    image: kiotlog/postgres
    networks:
      ttn:
        aliases:
          - kldb
          - postgres
    ports:
      - 127.0.0.1:7433:5432
    volumes:
      - ${COMPOSE_ROOTFS:-~/Build/srv/lib}/postgresql/10:/var/lib/postgresql/data
  
  klhr:
    image: kiotlog/httpreceiver
    depends_on:
      - postgres
      - emqtt
    networks:
      ttn:
        aliases:
          - klhr
          - httpreceiver
    ports:
      - 8080:8080
    command: --host 0.0.0.0 --mqttbroker emqtt 1883 --postgres kl_httpreceiver KlR3c3iv3r postgres 5432 trmpln

  decoder:
    image: kiotlog/decoder
    depends_on:
      - postgres
      - emqtt
    networks:
      ttn:
        aliases:
          - decoder
    command: --mqttbroker emqtt 1883 --postgres kl_decoder KlD3c0d3r postgres 5432 trmpln --topics /+/+/devices/+/up 

  klsn:
    image: kiotlog/klsnreceiver
    depends_on:
      - postgres
      - emqtt
    networks:
      ttn:
        aliases:
          - klsn
    command: --mqttbroker emqtt 1883 --postgres kl_snreceiver KLSnR3c3iv3r postgres 5432 trmpln


