version: "3"

networks:
  ttn:

services:
  grafana:
    image: fg2it/grafana-armhf:v4.6.3
    #volumes:
    #- lib/grafana:/var/lib/grafana
    networks:
      ttn:
        aliases:
        - grafana
    ports:
    - "3000:3000"

  mqtt:
    image: eclipse-mosquitto:arm32v7
    networks:
      ttn:
        aliases:
          - mqtt
          - mosquitto
    ports:
      - "1883:1883"

  mqtt-sn:
    build: ./rsmb
    image: rsmb
    networks:
      ttn:
        aliases:
          - rsmb
    ports:
      - "2883:2883/udp"

  mqtt-bridge:
    image: eclipse-mosquitto:arm32v7
    depends_on:
      - mqtt
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      ttn:
        aliases:
          - mqtt-bridge

  catalog:
    build: ./postgres
    image: kiotlog/catalog:arm32v7
    networks:
      ttn:
        aliases:
          - catalog
          - postgres
    ports:
      - 127.0.0.1:7432:5432
        #    volumes:
        #      - /var/lib/postgres/10:/var/lib/postgresql/data

  api:
    image: kiotlog/klapi:arm32v7
    networks:
      ttn:
        aliases:
          - api
    ports:
      - 80:8888
    environment:
      - host=0.0.0.0
      - port=8888
      - pguser=kl_webapi
      - pgpass=KlW3b4p1
      - pghost=catalog
      - pgport=5432
      - pgdb=trmpln

  klhr:
    image: kiotlog/httpreceiver:arm32v7
    depends_on:
      - catalog
      - mqtt
    networks:
      ttn:
        aliases:
          - klhr
          - httpreceiver
    ports:
      - 8080:8080
    command: --host 0.0.0.0 --mqttbroker mqtt 1883 --postgres kl_httpreceiver KlR3c3iv3r postgres 5432 trmpln

  decoder:
    image: kiotlog/decoder:arm32v7
    depends_on:
      - catalog
      - mqtt
    networks:
      ttn:
        aliases:
          - decoder
    command: --mqttbroker mqtt 1883 --postgres kl_decoder KlD3c0d3r postgres 5432 trmpln --topics /+/+/devices/+/up

  klsn:
    image: kiotlog/klsnreceiver:arm32v7
    depends_on:
      - catalog
      - mqtt
    networks:
      ttn:
        aliases:
          - klsn
    command: --mqttbroker mqtt 1883 --postgres kl_snreceiver KLSnR3c3iv3r postgres 5432 trmpln
