{
 "title": "Kiotlog Demo",
 "description": "Kiotlog for Trampoline",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SELECT distinct(d.device) FROM points p JOIN devices d ON d.id = p.device_id"
   },
   {
    "name": "Interval",
    "query": "1m, 5m, 10m, 30m, 1h, 3h, 6h, 12h, 1d, 1w, 2w, 1M, 3M, 1y"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature ($Device)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'temperature')::numeric) as temperature\nFROM\n  points p\nJOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\n  group by time\n  order by time\n"
    }
   ]
  },
  {
   "title": "Pressure ($Device)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'pressure')::numeric) as pressure\nFROM\n  points p\nJOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\n  group by time\n  order by time\n"
    }
   ]
  },
  {
   "title": "Humidity ($Device)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'humidity')::numeric) as humidity\nFROM\n  points p\nJOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\n  group by time\n  order by time\n"
    }
   ]
  },
  {
   "title": "Battery ($Device)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time, $Interval),\n  avg((data->>'battery')::numeric) as battery\nFROM\n  points p\nJOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\nGROUP BY\n  time\nORDER BY\n  time\n  "
    }
   ]
  },
  {
   "title": "Temperature ($Device)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'temperature')::numeric) as temperature,\n  avg((data->>'temperature_internal')::numeric) as temperature_internal\nFROM\n  points p\nJOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\n  group by time\n  order by time\n"
    }
   ]
  },
  {
   "title": "Pressure ($Device)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'pressure')::numeric) as pressure\nFROM\n  points p\nJOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\ngroup by time\norder by time\n"
    }
   ]
  },
  {
   "title": "Humidity ($Device)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'humidity')::numeric) as humidity\nFROM\n  points p\nJOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\n  group by time\n  order by time\n"
    }
   ]
  },
  {
   "title": "Battery ($Device)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time, $Interval),\n  avg((data->>'battery')::numeric) as battery\nFROM points p JOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time) and d.device = '$Device'\nGROUP BY\n  time\nORDER BY\n  time\n  \n\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'temperature')::numeric) as temperature,\n  d.device as metric\nFROM\n  points p JOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  time,\n  metric\nORDER BY\n  time,\n  metric\n  \n\n"
    }
   ]
  },
  {
   "title": "Pressures",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'pressure')::numeric) as pressure,\n  d.device as metric\nFROM\n  points p JOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  time,\n  metric\n  \n\n"
    }
   ]
  },
  {
   "title": "Humidities",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'humidity')::numeric) as humidity,\n  d.device as metric\nFROM\n  points p JOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  time,\n  metric\n  \n\n"
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $Interval),\n  avg((data->>'battery')::numeric) as battery,\n  d.device as metric\nFROM\n  points p JOIN devices d ON d.id = p.device_id\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  time,\n  metric\nORDER BY\n  time,\n  metric\n  \n\n"
    }
   ]
  }
 ]
}